// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3mtIJNnTuiPSyvkxo2ZV23SRIL5BHs_o',
    appId: '1:801569895884:web:2bf789484fc26a5f185969',
    messagingSenderId: '801569895884',
    projectId: 'blood-donation-4c9af',
    authDomain: 'blood-donation-4c9af.firebaseapp.com',
    storageBucket: 'blood-donation-4c9af.appspot.com',
    measurementId: 'G-M939G77LSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKsFw4Ud7ACh__yJi37fQihflOmZ3NC4',
    appId: '1:801569895884:android:36fb5e7a16d3adea185969',
    messagingSenderId: '801569895884',
    projectId: 'blood-donation-4c9af',
    storageBucket: 'blood-donation-4c9af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVlKzOojTwA6mFEoV-r7IXXPHR1hZ9MrQ',
    appId: '1:801569895884:ios:3e14e1bd2135931e185969',
    messagingSenderId: '801569895884',
    projectId: 'blood-donation-4c9af',
    storageBucket: 'blood-donation-4c9af.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVlKzOojTwA6mFEoV-r7IXXPHR1hZ9MrQ',
    appId: '1:801569895884:ios:a0c835fcac352095185969',
    messagingSenderId: '801569895884',
    projectId: 'blood-donation-4c9af',
    storageBucket: 'blood-donation-4c9af.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
